GET http://localhost:3001
###

POST http://localhost:3001/sign_up
Content-Type: application/json

{
    "matricule": "cm-uga-23FS0295",
    "nom":"mbroumsadja",
    "prenom":"emmanuel",
    "numero":"686824172",
    "filiere":"informatique",
    "email":"mbroumsadja@gmail.com"
}
###

POST  http://localhost:3001/login/cm-uga-23fs0295
###

POST http://localhost:3001/sign_up_admin
Content-Type: application/json

{
    "nom": "mbroumsadja",
    "prenom": "emmanuel",
    "email": "m.abdouM@admin.uga.cm",
    "password": "adminPasswor8789"
}
###

POST http://localhost:3001/login_admin
Content-Type: application/json

{
    "email":"m.abdouM@admin.uga.cm",
    "password":"adminPasswor8789"
}

###
GET http://localhost:3001/seance/cm-uga-23fs0295
###
GET http://localhost:3001/seance
###
GET http://localhost:3000/login
###
GET http://localhost:3000/sign_up;
###
POST http://localhost:3001/create_seance
Content-Type: application/json

[
  {
    "cours": "poo",
    "jour": "08-04-2025",
    "lieu": "Amphi 200",
    "debut": "08:00",
    "fin": "10:00",
    "enseignant": "Dr. Nkoulou",
    "filiere": "informatique",
    "niveau": "2",
    "create_by": "cm-uga-23FS0295"
    },
    {
    "cours": "infographie",
    "jour": "05-04-2025",
    "lieu": "Amphi 200",
    "debut": "10:30",
    "fin": "12:30",
    "enseignant": "Dr. Tchuente",
    "filiere": "informatique",
    "niveau": "2",
    "create_by": "cm-uga-23FS0295"
    },
    {
    "cours": "analyse 2",
    "jour": "06-04-2025",
    "lieu": "Salle B12",
    "debut": "08:00",
    "fin": "11:00",
    "enseignant": "Dr. Fotso",
    "filiere": "informatique",
    "niveau": "2",
    "create_by": "cm-uga-23FS0295"
  }
  ]

###
PUT  http://localhost:3001/update_seance/f3035eaa-12a2-4a1b-860c-6f0330f7c78b